### ISSUE TITLE
Log some information about the result of BinaryGeneratedFileObjectMatcher

### ISSUE THREAD

**Issue by NorbertSandor** [toolisticon/cute#63]
Is there a way to log the difference between the generated and the expected source files?
(Or at least log the contents of the generated source files...)

**Comment by tobiasstamann** [comment]
Hi,

All files will be automatically written to disk if a test is failing.

Therefore a temporary folder will be created in your build directory(target/cute_failingUnitTests/aRandomizedDirectoryName).

Please check the log of the failing test for details:

Here is a short snippet from the log output of a failing test, which shows which files are in the FileManager and the location on disk :
Failed tests: 
  BeanBuilderProcessorTest.test_valid_usage_with_custom_packagename:57 Compilation should have failed but succeeded

-------------------------------
-- GENERATED FILEOBJECTS: 
-------------------------------
{
  'GENERATED JAVA FILE OBJECTS' : [
    'mem://CLASS_OUTPUT/io/toolisticon/customPackage/TestcaseValidUsageWithCustomPackageBuilder.class' := '/Users/tobiasstamann/Projects/Opensource/bean-builder/processor/target/cute_failingUnitTests/lgpywhaxyv/io/toolisticon/customPackage/TestcaseValidUsageWithCustomPackageBuilder.class', 
    'mem://SOURCE_OUTPUT/io/toolisticon/customPackage/TestcaseValidUsageWithCustomPackageBuilder.java' := '/Users/tobiasstamann/Projects/Opensource/bean-builder/processor/target/cute_failingUnitTests/lgpywhaxyv/io/toolisticon/customPackage/TestcaseValidUsageWithCustomPackageBuilder.java', 
    'mem://CLASS_OUTPUT/io/toolisticon/spiap/processor/tests/TestcaseValidUsageWithCustomPackage.class' := '/Users/tobiasstamann/Projects/Opensource/bean-builder/processor/target/cute_failingUnitTests/lgpywhaxyv/io/toolisticon/spiap/processor/tests/TestcaseValidUsageWithCustomPackage.class', 
  ],
  'GENERATED FILE OBJECTS' :'No files were generated !!!'
}
-----------

So debugging of failing tests is really easy to do.

**Comment by tobiasstamann** [comment]
I have not yet included any logic to display a diff. At the moment it has to done manually.

**Comment by tobiasstamann** [comment]
So easiest way to provoke the files to be written is to chnage expected outcome (success <==> failing).

**Comment by NorbertSandor** [comment]
Thanks, examining the generated files is sufficient for me.
