### ISSUE TITLE
Is there a way to mock a JavaFileObject for Filer#getResource?

### ISSUE THREAD

**Issue by ChrisTrenkamp** [toolisticon/cute#77]
I would like to mock a file for the `Filer#getResource`  method to test my Annotation Processor's incremental capabilities.  It accumulates a list of annotated classes and dumps them into a text file.  On an incremental compilation, it reads in the file beforehand (`var previousFile = processingEnv.getFiler().getResource(StandardLocation.CLASS_OUTPUT, "", fileName);`), and checks each class to make sure it's still annotated, and if not, it removes the entry from the text file.

I have a working solution that's integrated with Eclipse and Gradle and would like to write a regression test for incremental compilations.  However, I'm not sure how to mock a Filer object so the above code snippet can retrieve it.

Is there a way to accomplish this?

**Comment by tobiasstamann** [comment]
Hi Chris,

to be honest i have never thought about doing such kind of incremental tests. 

First, it's not possible to "mock" the Filer class. It's a central part of the whole annotation processing and even testing process, so mocking it would break everything.

Unfortunately, the cute api doesn't currently support adding "existing" files to any StandardLocation.

But you can try to use cute's  "unit test" to achieve your goal.

Precondition:
- You must have a method in your processor does the processing for one single element and takes that element and additionally the processingEnv as parameters.
- Please add cutes PassIn annotation to the element you want to pass in (should be the one annotated with your annotation)

You can then create the unit test as following :
`
@Test
    public void testXXX(){


        CompileTestBuilder.unitTest()
                .useSource("/testcase/YourTestSource.java")
                .compilationShouldSucceed()
                .<YourProcessor, Element>defineTest(YourProcessor.class, new UnitTestForTestingAnnotationProcessors<YourProcessor,Element>(){
                    @Override
                    public void unitTest(YourProcessor processor, ProcessingEnvironment processingEnvironment, Element element) {

                        // now you can use the processing environment to create your precondition file before executing the test
                        FileObject fileObject = processingEnvironment.getFiler().createResource(StandardLocation.CLASS_OUTPUT, "", "yourFilename");
                        // Write file...

                        processor.processElement(element, processingEnvironment);

                        // Do assertions here or via cute api

                    }
                })
                .expectThatFileObjectExists(...)
                .executeTest();

    }
`

I will try to extend the cute api by a method to add preexisting files in the next couple of days. 

Have you tried my other framework [APTK](https://github.com/toolisticon/aptk)? It could help you to build your processors  in a more efficient way.

**Comment by ChrisTrenkamp** [comment]
I haven't tried your example yet, but I suspect that it's going to fail.  The Filer API does not allow you to re-open the same file, so when the annotation processor (correctly) tries to open the file with the `Filer#createResource method`, it will crash with a `FilerException`.

I'll take a look at APTK.

**Comment by tobiasstamann** [comment]
Yes, you are right. Had in mind that only altering of Source and Class files is forbidden. 

I guess in general incremental builds are really hard to handle when it comes to annotation processors. 
You cannot be sure if a changed and incremental compiled source file is affected by a processor which is triggered by an unchanged source file anyway. 

I guess thats why intellijs annotation processor support is that bad.
