### ISSUE TITLE
Clarify what `….contains(…)` is supposed to get handed in to succeed

### ISSUE THREAD

**Issue by odrotbohm** [toolisticon/cute#87]
I'm trying to assert a compiler error message that I generate via `TypeElementWrapper` and `….withCustomMessage("Invalid")`. I am using `Cute` to set up a verification pipeline and trying to use `….contains("Invalid")` to assert on the error message. However, I get:

```
java.lang.AssertionError: Haven't found expected compiler message string '[Invalid]' of kind 'ERROR'! (Check configuration : {\nwithLocale = null,
getSearchString = [Invalid],
atColumn = 19,
atSource = /org/jmolecules/annotation/processor/MyAggregateRoot.java,
getComparisonType = CONTAINS,
getKind = ERROR,
atLine = 27,
})

-------------------------------
-- ERROR MESSAGES: 
-------------------------------
[1]'/org/jmolecules/annotation/processor/MyAggregateRoot.java:27: error: Invalid
	MyAggregateRoot aggregate;
	                ^'
```

What's unclear from the method declaration of `contains(…)` is whether it's got to be handed in a whole element of the list of error messages. In that case I would have to copy the literal error message including line breaks into the call. I was assuming `contains(…)` would just take a snippet (as the Javadoc suggests) so that I can pipe in any expected substring.

All that said, the fluent API currently requires to *always* call `contains(…)` to be able to eventually call `executeTest()` on the returned object, which basically leaves me stuck now as I can't get the message verification to work. Does it make sense to allow skipping the message verification?

**Comment by tobiasstamann** [comment]
Hi, 

usually contains does just check if an error message contains all snippets you pass in. 

So it should work as described in the Javadoc and how you have expected it.

Can you please check if the column of the error message  is correct? 

And maybe post the MyAggregateRoot.java and your Test.

Are you trying to build some processors for JMolecules? I have spoken with Henning Schwentner about that in the past and have set up an example for it back then : https://github.com/tobiasstamann/jmolecules-processor

Best regards 

Tobias

**Comment by odrotbohm** [comment]
It indeed seems to be related to the column number. Which makes the error message quite misleading as it solely talks about the message string, not the position.

The sample source file uses tabs for indentation, and it looks like that results in the column value calculated differently. I am not particularly interested in the column, so I can just skip that.

Yes, indeed, the thing I'm working on is an APT for jMolecules. Thanks for the pointer, I'll definitely have a look for it for inspiration! 🙇

**Comment by tobiasstamann** [comment]
I have changed the debug output for existing compiler messages now. It now includes column numbers as well.
I will release it later today.

One more hint.  Try to add kind of error codes to your error messages. It's easier to test for specific message codes rather than for the message itself.

**Comment by odrotbohm** [comment]
Good one, thanks!

**Comment by tobiasstamann** [comment]
It's released in version 1.5.0 and will be available in a few hours

**Comment by odrotbohm** [comment]
Thank you! I'll have a look.

**Comment by odrotbohm** [comment]
[Upgraded](https://github.com/xmolecules/jmolecules-integrations/commit/988eb7d2430ec136ceba182614b28609939115aa)!
