### ISSUE TITLE
Test execution affecting the processor behavior in other tests

### ISSUE THREAD

**Issue by odrotbohm** [toolisticon/cute#88]
I've built some APT processor that verifies types based on whether they implement certain base types. To do that, I perform assignability checks like [this one](https://github.com/xmolecules/jmolecules-integrations/blob/0c008b28fafdee5a87ef2f83bb2ebc0054de264c/jmolecules-apt/src/main/java/org/jmolecules/annotation/processor/JMoleculesProcessor.java#L187).

I have tests verifying the verification (hah!) and they succeed if I execute the tests methods individually (inside my IDE for example). If I execute the entire test class, however, those tests involving the assignability checks fail. In other words, a type that was checked to implement a particular interface apparently does not implement that anymore, at least in the type-space that's considered during the test run.

I am not sure whether this is a problem in the contextual setup that `Cute` creates, or whether there's something wrong with my `Processor` implementation.

To verify:

1. Clone `https://github.com/xmolecules/jmolecules-integrations`
2. Switch into the `jmolecules-apt` module
3. Enable the two disabled test cases in [JMoleculesProcessorUnitTests](https://github.com/xmolecules/jmolecules-integrations/blob/0c008b28fafdee5a87ef2f83bb2ebc0054de264c/jmolecules-apt/src/test/java/org/jmolecules/annotation/processor/JMoleculesProcessorUnitTests.java#L32).
4. Run `mvn test -Dtest=JMoleculesProcessorUnitTests#detectsInvalidAggregateRootReferenceInImplementingAggregate` -> succeeds
5. Run `mvn test -Dtest=JMoleculesProcessorUnitTests#detectsInvalidAggregateRootReferenceInImplementingEntity` -> succeeds
6. Run `mvn test - Dtest=JMoleculesProcessorUnitTests` -> fails

**Comment by tobiasstamann** [comment]
Hi, i will take a look at it. 

But, Cute does provide a fresh Compile File Manager and Compiler that is initialized inside the executeTest method.
So it's unlikely that Cute is mixing up stuff between tests.

**Comment by tobiasstamann** [comment]
One more question, which IDE are you using?

**Comment by tobiasstamann** [comment]
I have checked your Tests,

your processor is a wildcard processor handling all annotations, but your source files of those two tests just have a sinfle Override annotation present on a method.

Your processor code 

```
rootElements.stream()
				.filter(TypeElement.class::isInstance)
				.map(TypeElement.class::cast)
				.flatMap(it -> {

					TypeElementWrapper wrap = TypeElementWrapper.wrap(it);
					return verifications.stream().map(verification -> verification.verify(wrap));

				}).reduce(true, (l, r) -> l && r);

		return true;
	}
```

is basically ignoring that ExecutableElement so compilation succeeds.

**Comment by odrotbohm** [comment]
I am using Eclipse.

But wait, which behavior is correct? The succceding or the failing one? Because depending on the mode of execution, the test result is different. Why is that? The `@Override` annotation is present in both cases.

**Comment by tobiasstamann** [comment]
Usually you need some kind of annotation you can rely on to make the processor work.

This could be for example an annotation placed on the package-info.java.  
This would allow you to test all TypeElement residing in those package.
But be warned: it's not possible to access sub-packages via the Processor api. So you would have to add that annotations in all packages you  want to check.

**Comment by tobiasstamann** [comment]
The succeding is correct. The processor only gets the methods ExecutableElement via the Overwrite annotation. So the element is filtered out and the processor does nothing. So the compilation succeeds.

**Comment by odrotbohm** [comment]
Well, in both standalone and multi-execution, the processor is invoked with a `TypeElement` of `MyAggregateRoot`. In the standalone execution, that element apparently implements `Identifiable` (via `AggregateRoot` and `Entity`), in the multi-execution it does not. I don't understand why that is. I also do not see the processor not being invoked at all, as you suggest. I even see it working when used in an example. It's solely the combined test execution that it apparently fails in.

**Comment by tobiasstamann** [comment]
The good thing is that those tests allow you to debug your processor. Just set some break points and you can check whats happening internally.

**Comment by tobiasstamann** [comment]
The processor is invoked. But not for a TypeElement, just for the annotated methods ExecutableElement - so it's filtered out by the stream filter expression.

**Comment by tobiasstamann** [comment]
One more thing, you are using _getRootElements_  which seems to be odd. I have never used that myself but according to Javadoc it can alead to altering behavior between compilations.

Usually you would  use getElementsAnnotatedWith() and use/loop over the annotations passed into the proccessor method.

**Comment by tobiasstamann** [comment]
Please consider to replace that wildcard mechanism by a kind of anchor annotation like i have mentioned before. Then you have a fixed entry point for checks and don't rely that there are any kind of other annotations present, which aren't guaranteed to be there. Package annotations could be good for that as i have mentioned before.

**Comment by odrotbohm** [comment]
I unfortunately can't do that as I have to support arrangements in which no annotations are at play at all.

That said, I was able to resolve the problem by moving away from `static` `TypeMirror` instances for the reference types in `JMoleculesDddVerification`. I assume that the reason for the issue is that the instances being static keeps the originally initialized ones around between processor runs that each initiate a new `Types` world. It thus would result in a mismatch for the second processor invocation. The first one sees the same `Identifiable` that the `MyAggregateRoot` references in its type hierarchy, as it stems from the same type pool the processor works with. In the second round, the one referred to from the type hierarchy is a different one than the instance initialized in the first run.

I'll close this. Thanks for your support here! 🙇

**Comment by tobiasstamann** [comment]
Ok, great. Forget about the things I mentioned about  getRootElements. It should work.  It will always provide a TypeElement or PackageElement if a package-info.java file exists. So you have to add a testcase for existing package info files.
